apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      release: kuber-demo-service-prometheus
  serviceMonitorNamespaceSelector: {}
