apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuber-demo-service-monitor
  namespace: istio-system
  labels:
    release: kuber-demo-service-prometheus
spec:
  selector:
    matchLabels:
      app: kuber-demo-service

  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scheme: http
